const FETCH_SEARCH_USERS = 'FETCH_SEARCH_USERS'
const SET_SEARCH_USERS = 'SET_SEARCH_USERS'
const CLEAR_SEARCH_USERS = 'CLEAR_SEARCH_USERS'

const FETCH_USER_REPOS = 'FETCH_USER_REPOS'
const SET_USER_REPOS = 'SET_USER_REPOS'

export {
  FETCH_SEARCH_USERS,
  SET_SEARCH_USERS,
  CLEAR_SEARCH_USERS,
  FETCH_USER_REPOS,
  SET_USER_REPOS,
}
